### Register User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "Kubra",
  "lastname": "Korkmaz",
  "email": "kybra.korkmaz@gmail.com",
  "password": "12345",
  "role": "ADMIN"
}

> {% client.global.set("auth-token", response.body.access_token);  %}

### Query the Demo endpoint
GET http://localhost:8080/api/v1/demo-controller
Authorization: Bearer {{auth-token}}

### Change the password
PATCH http://localhost:8080/api/v1/users/change-password
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "currentPassword": "12345",
  "newPassword": "password",
  "confirmPassword": "password"
}

###Login and update the token
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "kybra.korkmaz@gmail.com",
  "password": "password"
}

> {% client.global.set("new-auth-token", response.body.access_token); %}

### Query the Demo endpoint after password change
GET http://localhost:8080/api/v1/demo-controller
Authorization: Bearer {{new-auth-token}}

